In [ ]:
#Array is faster - It contains homogeneous(same) elements
#li = [1,2,"str"]
#arr = [1,2,3], ["r","a","z"]

#memory allocation is contiguous

In [8]:
import numpy as np
#np.array()

arr1 = np.array([1,2,3,4])
#print(arr1)
arr1

array([1, 2, 3, 4])

In [2]:
type(arr1)

numpy.ndarray

In [3]:
li = [1,2,3]
type(li)

list

In [9]:
type(arr1[0])

numpy.int32

In [14]:
arr2 = np.array([1,2,3,4], dtype=float)

arr2

array([1., 2., 3., 4.])

In [15]:
type(arr2[0])

numpy.float64

2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.

In [16]:
#arr_name.shape
#arr_name.ndim

import numpy as np

arr1 = np.array([1,2,3,4])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[1 2 3 4]
(4,)
1


In [24]:
#0 D

arr1 = np.array(100)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

100
()
0


In [21]:
#2D

arr1 = np.array([[1,2,3,4]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[1 2 3 4]]
(1, 4)
2


In [25]:
#3D

arr1 = np.array([[[1,2,3,4]]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[[1 2 3 4]]]
(1, 1, 4)
3


In [ ]:
#4 D

3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

In [26]:
#square matrix + diagonals should be one
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [29]:
#alternative

#np.eye

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [33]:
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [36]:
#np.full()
np.full((2,5),0) #(shape, fill_value)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

5. Create a numpy array that has the shape 3x5 and all the elements are 5

In [37]:
arr1 = np.full((3,5), 5)
print(arr1)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [41]:
#2nd way
arr2 = arr2 = np.ones((3,5))
print(arr2)

arr3 = arr2*5
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.

In [ ]:
#np.arange()
#np.random.randint()
#np.random.random

In [46]:
arr1 = np.arange(0, 101, 25) #(low, upper, step)
arr1

array([  0,  25,  50,  75, 100])

In [52]:
#ANs
arr2 = np.random.randint(low=0, high=100, size=25)
arr2

array([70, 72, 23, 11, 76, 85, 33, 12, 28, 61, 66,  3, 99, 85, 78, 90, 27,
       26, 75, 48, 95, 43, 42, 97, 28])

In [50]:
arr3 = np.random.random((5,2))
arr3

array([[0.50926805, 0.67215736],
       [0.28186629, 0.78233115],
       [0.84621038, 0.82765368],
       [0.73834064, 0.56515508],
       [0.67636318, 0.77566662]])

7. Create a numpy array with a shape 3x3 that has all elements as 1.

[1,1,1
 1,1,1
 1,1,1]

In [ ]:
#np.ones
#np.full

8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array

In [53]:
arr2 = np.random.randint(low=0, high=100, size=(2,3))
arr2

array([[75, 79, 12],
       [74, 91, 46]])

In [54]:
arr2.shape

(2, 3)

In [55]:
arr2.reshape(3,2) #(3,2), (6,1), (1,6)

array([[75, 79],
       [12, 74],
       [91, 46]])

In [56]:
arr2.reshape(6,1)

array([[75],
       [79],
       [12],
       [74],
       [91],
       [46]])

9.. Create a random array, with the range 0-100, with a size 50. Perform the
following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.

In [57]:
arr1 = np.random.randint(0,100,50)
print(arr1)

[56 40 17 21 44 66 15 53 93 49 96  7 27 89 92 58 70 35 20 53 28 34 98 37
 26 37 50 54 51 91 63 87  7 15 47 77 34 49 51 52 72 72 18 46 43  7 14 80
 13 50]


In [60]:
#a. Print the first ten elements of the array.
arr1[0:10] #0,1,2,3,4,5,6,7,8,9

print(arr1[:10])

[56 40 17 21 44 66 15 53 93 49]


In [61]:
#b. Print the last ten elements of the array
arr1[40:]

array([72, 72, 18, 46, 43,  7, 14, 80, 13, 50])

In [62]:
arr1[-10:]

array([72, 72, 18, 46, 43,  7, 14, 80, 13, 50])

In [63]:
#c. Print the elements from the indexes 10-25
arr1[10:26]

array([96,  7, 27, 89, 92, 58, 70, 35, 20, 53, 28, 34, 98, 37, 26, 37])

In [64]:
#d. Print the element at the index 22
arr1[22]

98

In [65]:
#e. Print the array using negative indexing.
arr1[-50:]

array([56, 40, 17, 21, 44, 66, 15, 53, 93, 49, 96,  7, 27, 89, 92, 58, 70,
       35, 20, 53, 28, 34, 98, 37, 26, 37, 50, 54, 51, 91, 63, 87,  7, 15,
       47, 77, 34, 49, 51, 52, 72, 72, 18, 46, 43,  7, 14, 80, 13, 50])

In [66]:
arr1[::-1] #reverse the array

array([50, 13, 80, 14,  7, 43, 46, 18, 72, 72, 52, 51, 49, 34, 77, 47, 15,
        7, 87, 63, 91, 51, 54, 50, 37, 26, 37, 98, 34, 28, 53, 20, 35, 70,
       58, 92, 89, 27,  7, 96, 49, 93, 53, 15, 66, 44, 21, 17, 40, 56])

In [67]:
#f. Print the last ten elements of the array, using negative indexing.

arr1[-10:]

array([72, 72, 18, 46, 43,  7, 14, 80, 13, 50])

#10.Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.

In [68]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [69]:
#a. Insert the element 6 at the end of the array.
arr2 = np.insert(arr1, 5, 6) #(array_name, index, value)
arr2

array([1, 2, 3, 4, 5, 6])

In [70]:
#b. Insert the element 10 at the beginning of the array.
arr3 = np.insert(arr1, 0, 10)
arr3

array([10,  1,  2,  3,  4,  5])

In [72]:
#c. Insert the element 30, before 4.
arr4 = np.insert(arr3, 4, 30)
arr4

array([10,  1,  2,  3, 30,  4,  5])

In [75]:
np.where(arr4==4)

(array([5], dtype=int64),)

In [ ]:
#d. Update the element 5 as 50.


In [79]:
#e. Delete the element 50 in the updated array
arr5 = np.delete(arr4, 6)
arr5

array([10,  1,  2,  3, 30,  4])

In [80]:
#f. Create a function to search for the element 30.

for i in range(0, len(arr5)): #0,1,2,3,4,5
    if(arr5[i] == 30):
        print(arr5[i], i)

30 4


In [81]:
#g. Sort the array in ascending order.
arr5.sort()
arr5

array([ 1,  2,  3,  4, 10, 30])